#!/bin/bash

CHROOT="/var/archlinux/root.x86_64"
COMMAND=$(echo $@ | tr ' ' '\ ')

doas cp /etc/resolv.conf $CHROOT/etc/resolv.conf
[[ -z $@ ]] && doas chroot $CHROOT /bin/su lemniskett \
    || doas chroot $CHROOT su -c "$COMMAND" lemniskett
