#!/bin/bash

CHROOT="/var/archlinux/root.x86_64"

mount -R /home $CHROOT/home
mount -t proc /proc $CHROOT/proc
mount -R /tmp $CHROOT/tmp
mount -R /sys $CHROOT/sys
mount -R /dev $CHROOT/dev
mount -R /run $CHROOT/run
mount -R /var/lib/dbus $CHROOT/var/lib/dbus
mount -R /lib/modules $CHROOT/lib/modules
mount -R /boot $CHROOT/boot

while true; do sleep 10800; done
