#!/bin/sh

. /etc/archbox.conf >/dev/null 2>&1

# Text colors/formatting
red="\033[38;5;1"
green="\033[38;5;2"
bold="\033[1m"
reset="\033[m"

err(){
    printf "${red}${bold}%s${reset}\n" "==> $*" 1>&2
    exit 1
}

msg(){
    printf "${green}${bold}%s${reset}\n" "==> $*" 1>&2
}

install_desktop(){
    mkdir -p ~/.local/share/applications/archbox
    for i in $@; do
        archbox readlink /usr/share/applications/$i >/dev/null 2>&1 \
            && cp "${CHROOT}"/$(archbox readlink /usr/share/applications/$i) ~/.local/share/applications/archbox \
            || cp "${CHROOT}"/usr/share/applications/$i "~/.local/share/applications/archbox"
        sed -i 's/Exec=/Exec=archbox\ /g' ~/.local/share/applications/archbox/$i
        sed -i '/TryExec=/d' ~/.local/share/applications/archbox/$i
    done
}

checkdep(){
    command -v $1 >/dev/null 2>&1 || err "Install $1!"
}

help_text(){
    printf "%s" "
USAGE: $0 <arguments>

OPTIONS:
  -i, --install FILE    Installs desktop entries in /usr/share/applications
  -r, --remove FILE     Removes desktop entries in ~/.local/share/applications/archbox
  -l, --list            List available desktop entries
  -s, --list-installed  List installed desktop entries
  -h, --help            Displays this help message

"
}

list(){
    for i in $*/*; do
        printf "%s\n" "$i"
    done
}

case $1 in 
    -i|--install)
        checkdep update-desktop-database
        install_desktop ${@#$1}
        update-desktop-database
        exit $?
    ;;
    -r|--remove)
        checkdep update-desktop-database
        selected_entry=${@#$1}
        for i in $selected_entry; do
            rm ~/.local/share/applications/archbox/$i
        done
        update-desktop-database
        exit $?
    ;;
    -h|--help)
        help_text
        exit 0
    ;;
    -l|--list)
        list "${CHROOT}"/usr/share/applications
    ;;
    -s|--list-installed)
        mkdir -p ~/.local/share/applications/archbox
        list ~/.local/share/applications/archbox
    ;;
    *)
        checkdep zenity
        checkdep sed
        checkdep update-desktop-database
        action="$(zenity --list --radiolist --title 'Archbox Desktop Manager' \
            --height=200 --width=450 --column 'Select' --column 'Action' \
            --text 'What do you want to do?' \
             FALSE 'Install desktop entries' FALSE 'Remove desktop entries')"
        case $action in
            'Install desktop entries')
                zenity_entry="$(list "${CHROOT}"/usr/share/applications | sed 's/\ /\ FALSE\ /g')"
                selected_entry=$(zenity --list --checklist --height=500 --width=450 \
                    --title="Archbox Desktop Manager" \
                    --text "Select .desktop entries those you want to install" \
                    --column "Select" --column "Applications" \
                    FALSE $zenity_entry | sed 's/|/\ /g')
                [ $selected_entry ] || exit 1
                install_desktop $selected_entry
                update-desktop-database
                exit 0
            ;;
            'Remove desktop entries')
                list_desktop="$(list ~/.local/share/applications/archbox)"
                [ $list_desktop = "*" ] && zenity --info --title "Archbox Desktop Manager" \
                    --text "No .desktop files installed" --width=300 && exit 1
                zenity_entry="$(printf "%s" "$list_desktop" | sed 's/\ /\ FALSE\ /g')"
                selected_entry=$(zenity --list --checklist --height=500 --width=450 \
                --title="Archbox Desktop Manager" \
                --text "Select .desktop entries those you want to remove" \
                --column "Select" --column "Applications" \
                FALSE $zenity_entry | sed 's/|/\ /g')
                [[ -z $selected_entry ]] && exit 1
                for i in $selected_entry; do
                    rm ~/.local/share/applications/archbox/$i
                done
                update-desktop-database
                exit $?
            ;;
        esac
        exit 1
    ;;
esac    
