#!/bin/bash

source /etc/archbox.conf

mount -R /home $CHROOT/home
mount -t proc /proc $CHROOT/proc
mount -R /tmp $CHROOT/tmp
mount -R /sys $CHROOT/sys
mount -R /dev $CHROOT/dev
mount -R /run $CHROOT/run
mount -R /lib/modules $CHROOT/lib/modules
mount -R /boot $CHROOT/boot

# Allow chroot enviroment to access host's machine id
# to be able to connect to host's pulseaudio.
# Comment if the chroot enviroment is not able to connect 
# to host's pulseaudio, you may want to start pulseaudio in 
# the chroot instead.
mount -R /var/lib/dbus $CHROOT/var/lib/dbus

# Runit will re-execute scripts those are finished,
# so we create a neverending loop.
while true; do sleep 10800; done
